### ISSUE TITLE
Code error on run

### ISSUE THREAD

**Issue by dkebler** [jirutka/rsub-client#1] opened 2014-11-19 01:46 UTC
Can I get some help on getting rsub installed via pip.  It has errors

ran pip install rsub
below is output, then ran rsub --help, output also below
running ubuntu 14.10 with python 2.7.x
(fyi, I can get rmate running fine under ruby)

ubuntu@vm-ub-sr-1410:~$ sudo pip install rsub
Downloading/unpacking rsub
  Downloading rsub-1.0.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/rsub/setup.py) egg_info for package rsub
    warning: pypandoc module not found, could not convert Markdown to RST

Requirement already satisfied (use --upgrade to upgrade): docopt>=0.5.0 in /usr/local/lib/python2.7/dist-packages (from rsub)
Installing collected packages: rsub
  Running setup.py install for rsub
    warning: pypandoc module not found, could not convert Markdown to RST
    changing mode of build/scripts-2.7/rsub from 644 to 755

```
changing mode of /usr/local/bin/rsub to 755
```

Successfully installed rsub
Cleaning up...

ubuntu@vm-ub-sr-1410:~$ rsub --help
Traceback (most recent call last):
  File "/usr/local/bin/rsub", line 405, in <module>
    main()
  File "/usr/local/bin/rsub", line 349, in main
    conf.update(read_settings_rcfiles())
  File "/usr/local/bin/rsub", line 121, in read_settings_rcfiles
    return config.to_dict()
  File "/usr/local/bin/rsub", line 170, in to_dict
    return dict(self.items(self.FAKE_SECTION))
  File "/usr/lib/python2.7/ConfigParser.py", line 642, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'NOSECTION'

**Comment by jirutka** [comment] 2015-08-10 11:59
Sorry for very looong delay, I’ve somehow missed this issues. However, I can’t reproduce this problem, it works for me on every machine.

**Comment by leal-alvaro** [comment] 2015-10-20 11:47
I see this exact same problem when I try to edit a file that is not in the current directory, using an absolute path. 

For example: 

This fails with the error message described above:
$ rsub /etc/apache2/apache2.conf 

This works perfectly:
$ cd /etc/apache2 && rsub apache2.conf

EDIT: Fixed with $ touch ~/.rsubrc

**Closed as completed** 2015-12-03 01:14 UTC

**Comment by jirutka** [comment] 2015-12-03 01:25
> EDIT: Fixed with $ touch ~/.rsubrc

This was the key, thanks! I feel stupid that I wasn’t able to figure it out myself…

I’ve fixed it and released 1.0.2.
